### ISSUE TITLE
No access to page for anonymous users

### ISSUE THREAD

**Issue by eidoander** [webaccess/com.webaccessglobal.simpledonate#44] opened 2016-03-07 04:39 UTC
Using Simple Donate 1.1, CiviCRM 4.6.8 on Drupal 7.39. Anonymous users get error below. How do I configure so that anonymous users can access my contribution page? Thanks!

"id is not a valid integer"

**Comment by kurund** [comment] 2016-03-07 11:45
Duplicate of https://github.com/webaccess/com.webaccessglobal.simpledonate/issues/35

**Closed by kurund** 2016-03-07 11:45 UTC

**Comment by eidoander** [comment] 2016-03-07 12:11
Korund, please advise me. My file at sites/all/modules/civicrm/CRM/Mailing/Info.php, lines 58-72, looks like this:


  /**
   * Get AngularJS modules and their dependencies
   *
   * @return array
   *   list of modules; same format as CRM_Utils_Hook::angularModules(&$angularModules)
   * @see CRM_Utils_Hook::angularModules
   */
  public function getAngularModules() {
    $result = array();
    $result['crmMailing'] = array(
      'ext' => 'civicrm',
      'js' => array(
        'ang/crmMailing.js',
        'ang/crmMailing/*.js',
      ),

Where do I insert the corrected lines?

**Comment by eidoander** [comment] 2016-03-07 12:40
I added the three lines of the patch (never done this before) replacing the lines indicated. Seems to work now. Thanks.
